FROM php:8.3-fpm

# System packages + LibreOffice + MySQL client + PHP extensions
RUN apt-get update && apt-get install -y \
    bash \
    procps \
    git \
    unzip \
    zip \
    mysql-client \
    libzip-dev \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    libreoffice \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install \
        pdo \
        pdo_mysql \
        zip \
        gd \
        bcmath \
    && rm -rf /var/lib/apt/lists/*

# Composer
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html

# sanity checks (nefailne build)
RUN php -m | grep bcmath || true
RUN soffice --version || true

EXPOSE 9000

CMD ["php-fpm"]
